import { registerIcon } from '@barry127/bui/Icon';

import activity from '../icons/activity';
import airplay from '../icons/airplay';
import alertCircle from '../icons/alert-circle';
import alertOctagon from '../icons/alert-octagon';
import alertTriange from '../icons/alert-triangle';
import alignCenter from '../icons/align-center';
import alignJustify from '../icons/align-justify';
import alignLeft from '../icons/align-left';
import alignRight from '../icons/align-right';
import anchor from '../icons/anchor';
import aperture from '../icons/aperture';
import archive from '../icons/archive';
import arrowDownCircle from '../icons/arrow-down-circle';
import arrowDownLeft from '../icons/arrow-down-left';
import arrowDownRight from '../icons/arrow-down-right';
import arrowDown from '../icons/arrow-down';
import arrowLeftCircle from '../icons/arrow-left-circle';
import arrowLeft from '../icons/arrow-left';
import arrowRightCircle from '../icons/arrow-right-circle';
import arrowRight from '../icons/arrow-right';
import arrowUpCircle from '../icons/arrow-up-circle';
import arrowUpLeft from '../icons/arrow-up-left';
import arrowUpRight from '../icons/arrow-up-right';
import arrowUp from '../icons/arrow-up';
import atSign from '../icons/at-sign';
import award from '../icons/award';
import barChart2 from '../icons/bar-chart-2';
import barChart from '../icons/bar-chart';
import batteryCharging from '../icons/battery-charging';
import battery from '../icons/battery';
import bellOff from '../icons/bell-off';
import bell from '../icons/bell';
import bluetooth from '../icons/bluetooth';
import bold from '../icons/bold';
import bookOpen from '../icons/book-open';
import book from '../icons/book';
import bookmark from '../icons/bookmark';
import box from '../icons/box';
import briefcase from '../icons/briefcase';
import calendar from '../icons/calendar';
import cameraOff from '../icons/camera-off';
import camera from '../icons/camera';
import cast from '../icons/cast';
import checkCircle from '../icons/check-circle';
import checkSquare from '../icons/check-square';
import check from '../icons/check';
import chevronDown from '../icons/chevron-down';
import chevronLeft from '../icons/chevron-left';
import chevronRight from '../icons/chevron-right';
import chevronUp from '../icons/chevron-up';
import chevronsDown from '../icons/chevrons-down';
import chevronsLeft from '../icons/chevrons-left';
import chevronsRight from '../icons/chevrons-right';
import chevronsUp from '../icons/chevrons-up';
import chrome from '../icons/chrome';
import circle from '../icons/circle';
import clipboard from '../icons/clipboard';
import clock from '../icons/clock';
import cloudDrizzle from '../icons/cloud-drizzle';
import cloudLightning from '../icons/cloud-lightning';
import cloudOff from '../icons/cloud-off';
import cloudRain from '../icons/cloud-rain';
import cloudSnow from '../icons/cloud-snow';
import cloud from '../icons/cloud';
import code from '../icons/code';
import codepen from '../icons/codepen';
import command from '../icons/command';
import compass from '../icons/compass';
import copy from '../icons/copy';
import cornerDownLeft from '../icons/corner-down-left';
import cornerDownRight from '../icons/corner-down-right';
import cornerLeftDown from '../icons/corner-left-down';
import cornerLeftUp from '../icons/corner-left-up';
import cornerRightDown from '../icons/corner-right-down';
import cornerRightUp from '../icons/corner-right-up';
import cornerUpLeft from '../icons/corner-up-left';
import cornerUpRight from '../icons/corner-up-right';
import cpu from '../icons/cpu';
import creditCard from '../icons/credit-card';
import crop from '../icons/crop';
import crosshair from '../icons/crosshair';
import database from '../icons/database';
import delete_ from '../icons/delete';
import disc from '../icons/disc';
import dollarSign from '../icons/dollar-sign';
import downloadCloud from '../icons/download-cloud';
import download from '../icons/download';
import droplet from '../icons/droplet';
import edit2 from '../icons/edit-2';
import edit3 from '../icons/edit-3';
import edit from '../icons/edit';
import externalLink from '../icons/external-link';
import eyeOff from '../icons/eye-off';
import eye from '../icons/eye';
import facebook from '../icons/facebook';
import fastForward from '../icons/fast-forward';
import feather from '../icons/feather';
import fileMinus from '../icons/file-minus';
import filePlus from '../icons/file-plus';
import fileText from '../icons/file-text';
import file from '../icons/file';
import film from '../icons/film';
import filter from '../icons/filter';
import flag from '../icons/flag';
import folderMinus from '../icons/folder-minus';
import folderPlus from '../icons/folder-plus';
import folder from '../icons/folder';
import gift from '../icons/gift';
import gitBranch from '../icons/git-branch';
import gitCommit from '../icons/git-commit';
import gitMerge from '../icons/git-merge';
import gitPullRequest from '../icons/git-pull-request';
import github from '../icons/github';
import gitlab from '../icons/gitlab';
import globe from '../icons/globe';
import grid from '../icons/grid';
import hardDrive from '../icons/hard-drive';
import hash from '../icons/hash';
import headphones from '../icons/headphones';
import heart from '../icons/heart';
import helpCircle from '../icons/help-circle';
import home from '../icons/home';
import image from '../icons/image';
import inbox from '../icons/inbox';
import info from '../icons/info';
import instagram from '../icons/instagram';
import italic from '../icons/italic';
import layers from '../icons/layers';
import layout from '../icons/layout';
import lifeBuoy from '../icons/life-buoy';
import link2 from '../icons/link-2';
import link from '../icons/link';
import linkedin from '../icons/linkedin';
import list from '../icons/list';
import loader from '../icons/loader';
import lock from '../icons/lock';
import logIn from '../icons/log-in';
import logOut from '../icons/log-out';
import mail from '../icons/mail';
import mapPin from '../icons/map-pin';
import map from '../icons/map';
import maximize2 from '../icons/maximize-2';
import maximize from '../icons/maximize';
import menu from '../icons/menu';
import messageCircle from '../icons/message-circle';
import messageSquare from '../icons/message-square';
import micOff from '../icons/mic-off';
import mic from '../icons/mic';
import minimize2 from '../icons/minimize-2';
import minimize from '../icons/minimize';
import minusCircle from '../icons/minus-circle';
import minusSquare from '../icons/minus-square';
import minus from '../icons/minus';
import monitor from '../icons/monitor';
import moon from '../icons/moon';
import moreHorizontal from '../icons/more-horizontal';
import moreVertical from '../icons/more-vertical';
import move from '../icons/move';
import music from '../icons/music';
import navigation2 from '../icons/navigation-2';
import navigation from '../icons/navigation';
import octagon from '../icons/octagon';
import package_ from '../icons/package';
import paperclip from '../icons/paperclip';
import pauseCircle from '../icons/pause-circle';
import pause from '../icons/pause';
import percent from '../icons/percent';
import phoneCall from '../icons/phone-call';
import phoneForwarded from '../icons/phone-forwarded';
import phoneIncoming from '../icons/phone-incoming';
import phoneMissed from '../icons/phone-missed';
import phoneOff from '../icons/phone-off';
import phoneOutgoing from '../icons/phone-outgoing';
import phone from '../icons/phone';
import pieChart from '../icons/pie-chart';
import playCircle from '../icons/play-circle';
import play from '../icons/play';
import plusCircle from '../icons/plus-circle';
import plusSquare from '../icons/plus-square';
import plus from '../icons/plus';
import pocket from '../icons/pocket';
import power from '../icons/power';
import printer from '../icons/printer';
import radio from '../icons/radio';
import refreshCcw from '../icons/refresh-ccw';
import refreshCw from '../icons/refresh-cw';
import repeat from '../icons/repeat';
import rewind from '../icons/rewind';
import rotateCcw from '../icons/rotate-ccw';
import rotateCw from '../icons/rotate-cw';
import rss from '../icons/rss';
import save from '../icons/save';
import scissors from '../icons/scissors';
import search from '../icons/search';
import send from '../icons/send';
import server from '../icons/server';
import settings from '../icons/settings';
import share2 from '../icons/share-2';
import share from '../icons/share';
import shieldOff from '../icons/shield-off';
import shield from '../icons/shield';
import shoppingBag from '../icons/shopping-bag';
import shoppingCart from '../icons/shopping-cart';
import shuffle from '../icons/shuffle';
import sidebar from '../icons/sidebar';
import skipBack from '../icons/skip-back';
import skipForward from '../icons/skip-forward';
import slack from '../icons/slack';
import slash from '../icons/slash';
import sliders from '../icons/sliders';
import smartphone from '../icons/smartphone';
import speaker from '../icons/speaker';
import square from '../icons/square';
import star from '../icons/star';
import stopCircle from '../icons/stop-circle';
import sun from '../icons/sun';
import sunrise from '../icons/sunrise';
import sunset from '../icons/sunset';
import tablet from '../icons/tablet';
import tag from '../icons/tag';
import target from '../icons/target';
import terminal from '../icons/terminal';
import thermometer from '../icons/thermometer';
import thumbsDown from '../icons/thumbs-down';
import thumbsUp from '../icons/thumbs-up';
import toggleLeft from '../icons/toggle-left';
import toggleRight from '../icons/toggle-right';
import trash2 from '../icons/trash-2';
import trash from '../icons/trash';
import trendingDown from '../icons/trending-down';
import trendingUp from '../icons/trending-up';
import triangle from '../icons/triangle';
import truck from '../icons/truck';
import tv from '../icons/tv';
import twitter from '../icons/twitter';
import type_ from '../icons/type';
import umbrella from '../icons/umbrella';
import underline from '../icons/underline';
import unlock from '../icons/unlock';
import uploadCloud from '../icons/upload-cloud';
import upload from '../icons/upload';
import userCheck from '../icons/user-check';
import userMinus from '../icons/user-minus';
import userPlus from '../icons/user-plus';
import userX from '../icons/user-x';
import user from '../icons/user';
import users from '../icons/users';
import videoOff from '../icons/video-off';
import video from '../icons/video';
import voicemail from '../icons/voicemail';
import volume1 from '../icons/volume-1';
import volume2 from '../icons/volume-2';
import volumeX from '../icons/volume-x';
import volume from '../icons/volume';
import watch from '../icons/watch';
import wifiOff from '../icons/wifi-off';
import wifi from '../icons/wifi';
import wind from '../icons/wind';
import xCircle from '../icons/x-circle';
import xSquare from '../icons/x-square';
import x from '../icons/x';
import youtube from '../icons/youtube';
import zapOff from '../icons/zap-off';
import zap from '../icons/zap';
import zoomIn from '../icons/zoom-in';
import zoomOut from '../icons/zoom-out';

registerIcon(activity);
registerIcon(airplay);
registerIcon(alertCircle);
registerIcon(alertOctagon);
registerIcon(alertTriange);
registerIcon(alignCenter);
registerIcon(alignJustify);
registerIcon(alignLeft);
registerIcon(alignRight);
registerIcon(anchor);
registerIcon(aperture);
registerIcon(archive);
registerIcon(arrowDownCircle);
registerIcon(arrowDownLeft);
registerIcon(arrowDownRight);
registerIcon(arrowDown);
registerIcon(arrowLeftCircle);
registerIcon(arrowLeft);
registerIcon(arrowRightCircle);
registerIcon(arrowRight);
registerIcon(arrowUpCircle);
registerIcon(arrowUpLeft);
registerIcon(arrowUpRight);
registerIcon(arrowUp);
registerIcon(atSign);
registerIcon(award);
registerIcon(barChart2);
registerIcon(barChart);
registerIcon(batteryCharging);
registerIcon(battery);
registerIcon(bellOff);
registerIcon(bell);
registerIcon(bluetooth);
registerIcon(bold);
registerIcon(bookOpen);
registerIcon(book);
registerIcon(bookmark);
registerIcon(box);
registerIcon(briefcase);
registerIcon(calendar);
registerIcon(cameraOff);
registerIcon(camera);
registerIcon(cast);
registerIcon(checkCircle);
registerIcon(checkSquare);
registerIcon(check);
registerIcon(chevronDown);
registerIcon(chevronLeft);
registerIcon(chevronRight);
registerIcon(chevronUp);
registerIcon(chevronsDown);
registerIcon(chevronsLeft);
registerIcon(chevronsRight);
registerIcon(chevronsUp);
registerIcon(chrome);
registerIcon(circle);
registerIcon(clipboard);
registerIcon(clock);
registerIcon(cloudDrizzle);
registerIcon(cloudLightning);
registerIcon(cloudOff);
registerIcon(cloudRain);
registerIcon(cloudSnow);
registerIcon(cloud);
registerIcon(code);
registerIcon(codepen);
registerIcon(command);
registerIcon(compass);
registerIcon(copy);
registerIcon(cornerDownLeft);
registerIcon(cornerDownRight);
registerIcon(cornerLeftDown);
registerIcon(cornerLeftUp);
registerIcon(cornerRightDown);
registerIcon(cornerRightUp);
registerIcon(cornerUpLeft);
registerIcon(cornerUpRight);
registerIcon(cpu);
registerIcon(creditCard);
registerIcon(crop);
registerIcon(crosshair);
registerIcon(database);
registerIcon(delete_);
registerIcon(disc);
registerIcon(dollarSign);
registerIcon(downloadCloud);
registerIcon(download);
registerIcon(droplet);
registerIcon(edit2);
registerIcon(edit3);
registerIcon(edit);
registerIcon(externalLink);
registerIcon(eyeOff);
registerIcon(eye);
registerIcon(facebook);
registerIcon(fastForward);
registerIcon(feather);
registerIcon(fileMinus);
registerIcon(filePlus);
registerIcon(fileText);
registerIcon(file);
registerIcon(film);
registerIcon(filter);
registerIcon(flag);
registerIcon(folderMinus);
registerIcon(folderPlus);
registerIcon(folder);
registerIcon(gift);
registerIcon(gitBranch);
registerIcon(gitCommit);
registerIcon(gitMerge);
registerIcon(gitPullRequest);
registerIcon(github);
registerIcon(gitlab);
registerIcon(globe);
registerIcon(grid);
registerIcon(hardDrive);
registerIcon(hash);
registerIcon(headphones);
registerIcon(heart);
registerIcon(helpCircle);
registerIcon(home);
registerIcon(image);
registerIcon(inbox);
registerIcon(info);
registerIcon(instagram);
registerIcon(italic);
registerIcon(layers);
registerIcon(layout);
registerIcon(lifeBuoy);
registerIcon(link2);
registerIcon(link);
registerIcon(linkedin);
registerIcon(list);
registerIcon(loader);
registerIcon(lock);
registerIcon(logIn);
registerIcon(logOut);
registerIcon(mail);
registerIcon(mapPin);
registerIcon(map);
registerIcon(maximize2);
registerIcon(maximize);
registerIcon(menu);
registerIcon(messageCircle);
registerIcon(messageSquare);
registerIcon(micOff);
registerIcon(mic);
registerIcon(minimize2);
registerIcon(minimize);
registerIcon(minusCircle);
registerIcon(minusSquare);
registerIcon(minus);
registerIcon(monitor);
registerIcon(moon);
registerIcon(moreHorizontal);
registerIcon(moreVertical);
registerIcon(move);
registerIcon(music);
registerIcon(navigation2);
registerIcon(navigation);
registerIcon(octagon);
registerIcon(package_);
registerIcon(paperclip);
registerIcon(pauseCircle);
registerIcon(pause);
registerIcon(percent);
registerIcon(phoneCall);
registerIcon(phoneForwarded);
registerIcon(phoneIncoming);
registerIcon(phoneMissed);
registerIcon(phoneOff);
registerIcon(phoneOutgoing);
registerIcon(phone);
registerIcon(pieChart);
registerIcon(playCircle);
registerIcon(play);
registerIcon(plusCircle);
registerIcon(plusSquare);
registerIcon(plus);
registerIcon(pocket);
registerIcon(power);
registerIcon(printer);
registerIcon(radio);
registerIcon(refreshCcw);
registerIcon(refreshCw);
registerIcon(repeat);
registerIcon(rewind);
registerIcon(rotateCcw);
registerIcon(rotateCw);
registerIcon(rss);
registerIcon(save);
registerIcon(scissors);
registerIcon(search);
registerIcon(send);
registerIcon(server);
registerIcon(settings);
registerIcon(share2);
registerIcon(share);
registerIcon(shieldOff);
registerIcon(shield);
registerIcon(shoppingBag);
registerIcon(shoppingCart);
registerIcon(shuffle);
registerIcon(sidebar);
registerIcon(skipBack);
registerIcon(skipForward);
registerIcon(slack);
registerIcon(slash);
registerIcon(sliders);
registerIcon(smartphone);
registerIcon(speaker);
registerIcon(square);
registerIcon(star);
registerIcon(stopCircle);
registerIcon(sun);
registerIcon(sunrise);
registerIcon(sunset);
registerIcon(tablet);
registerIcon(tag);
registerIcon(target);
registerIcon(terminal);
registerIcon(thermometer);
registerIcon(thumbsDown);
registerIcon(thumbsUp);
registerIcon(toggleLeft);
registerIcon(toggleRight);
registerIcon(trash2);
registerIcon(trash);
registerIcon(trendingDown);
registerIcon(trendingUp);
registerIcon(triangle);
registerIcon(truck);
registerIcon(tv);
registerIcon(twitter);
registerIcon(type_);
registerIcon(umbrella);
registerIcon(underline);
registerIcon(unlock);
registerIcon(uploadCloud);
registerIcon(upload);
registerIcon(userCheck);
registerIcon(userMinus);
registerIcon(userPlus);
registerIcon(userX);
registerIcon(user);
registerIcon(users);
registerIcon(videoOff);
registerIcon(video);
registerIcon(voicemail);
registerIcon(volume1);
registerIcon(volume2);
registerIcon(volumeX);
registerIcon(volume);
registerIcon(watch);
registerIcon(wifiOff);
registerIcon(wifi);
registerIcon(wind);
registerIcon(xCircle);
registerIcon(xSquare);
registerIcon(x);
registerIcon(youtube);
registerIcon(zapOff);
registerIcon(zap);
registerIcon(zoomIn);
registerIcon(zoomOut);

export { default } from './list';
